/*
 * Calculator API
 *
 * A simple calculator API that performs basic arithmetic operations based on the provided header.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using IO.Swagger.Models;
using System.Web.Http;
using ArithmeticExecuteServices.Services.Interfaces;
using FromBodyAttribute = Microsoft.AspNetCore.Mvc.FromBodyAttribute;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;
using RouteAttribute = Microsoft.AspNetCore.Mvc.RouteAttribute;
using System.ComponentModel.DataAnnotations;
using Swashbuckle.AspNetCore.Annotations;

namespace IO.Swagger.Controllers
{
    public class ArithmeticExecuteController : ApiController
    {
        private readonly IArithmeticExecuteService _arithmeticExecutService;

        public ArithmeticExecuteController(IArithmeticExecuteService arithmeticExecutService)
        {
            _arithmeticExecutService = arithmeticExecutService;
        }

        [HttpPost]
        //ניווט ל API
        [Route("/v1/calculate")]
        [SwaggerOperation("ArithmeticExecuteFunc")]
        public int ArithmeticExecuteFunc([FromBody] ArithmeticExecuteModel request, [FromHeader][Required()] string operationRequest)
        {
            var result = _arithmeticExecutService.ArithmeticExecute(request, operationRequest);
            return result;
        }
    }
}